export interface ChangelogEntry {
  version: string      // e.g. "1.003"
  date: string         // YYYY-MM-DD
  title: string
  changes: string[]
}

export const APP_VERSION = '1.074'

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '1.074',
    date: '2026-06-11',
    title: '🔧 紧急修复：用户鬼打墙卡在 onboarding 循环',
    changes: [
      '🐛 修复 (app)/layout.tsx：is_suspended 字段未迁移时查询失败导致 profile=null，触发无限 onboarding 重定向',
      '✅ 改为先尝试完整查询，失败时回退至仅查询 onboarding_done，保证用户可正常进入 app',
    ],
  },
  {
    version: '1.073',
    date: '2026-06-10',
    title: '🛡️ 管理员后台 — 监控、分析、访问控制、AI 模型切换',
    changes: [
      '🔐 管理员从同一登录页登录 (ADMIN / P@ssw0rd@123)，跳转至专属后台',
      '📊 后台概览：用户数、活跃用户、本月新增、交易总量、MYR 总额图表',
      '👥 用户管理：分页列表、搜索、暂停/恢复账号（同步 Supabase Auth）',
      '📈 平台分析：用户增长、月度交易量、热门支出类别、最活跃用户',
      '🤖 AI 模型切换：管理员可从后台实时切换 Standard/HQ Gemini 模型',
      '🚫 被暂停用户访问 app 时显示"账号已暂停"页面',
      '🔧 修复 proxy.ts 路由守卫：将 /api/admin 和 /admin 加入公开路径白名单',
      '📊 修复功能采用率百分比：aiParseUsers 和 stockUsers 改为统计不重复用户数',
    ],
  },
  {
    version: '1.072',
    date: '2026-06-06',
    title: '✅ 彻底修复编辑交易白框 — Drawer 换成 Sheet',
    changes: [
      '🎯 根本原因：vaul Drawer 内置键盘 JS 与 iOS Chrome 冲突，造成白框',
      '✅ EditTransactionSheet 改用 Sheet (base-ui Dialog)，与确认交易页面一致',
      '🔧 Sheet 用 fixed bottom:0 + overflow-y-auto，iOS 原生处理键盘位置，无白框',
      '🧹 移除 sticky footer，按钮回归滚动内容区',
    ],
  },
  {
    version: '1.071',
    date: '2026-06-06',
    title: '修复编辑抽屉白框 — 滚动区改用 flex-1',
    changes: [
      '🐛 vaul 缩小 drawer 高度后，max-h-[55dvh] 固定值不跟着缩 → 内部出现空白',
      '✅ 滚动区改为 flex-1 min-h-0，随 drawer 高度自动填充，彻底消除白框',
      '🔧 底部 footer 减少多余 padding-bottom',
    ],
  },
  {
    version: '1.070',
    date: '2026-06-06',
    title: '✅ 真·修复 iOS 键盘白框 — 移除 interactiveWidget',
    changes: [
      '🎯 真正元凶：viewport 的 interactiveWidget:resizes-content',
      '🔍 vaul 内置键盘处理依赖 window.innerHeight 在键盘弹出时保持不变',
      '🐛 resizes-content 让 innerHeight 跟着键盘一起缩小 → vaul 算不出键盘高度 → Drawer 维持原高+bottom:0 → 大白框',
      '✅ 移除该设置，恢复默认 resizes-visual，vaul 自动把 Drawer 缩放并顶到键盘上方',
    ],
  },
  {
    version: '1.069',
    date: '2026-06-06',
    title: '彻底修复 iOS 键盘白框 — 撤销所有 transform hack',
    changes: [
      '🎯 找到真正原因：vaul 自身用 transform 做动画，我们的 translateY 与它冲突',
      '🐛 多余的 translateY 把 Drawer 又往上推一段，露出 vaul 白色 ::after 伪元素=白框',
      '✅ 移除所有 keyboard transform hack，交给浏览器原生处理',
      '🧹 删除不再需要的 IOSKeyboardFix 组件',
    ],
  },
  {
    version: '1.067',
    date: '2026-06-06',
    title: '真正修复 iOS 键盘白框 (正确 vaul 选择器)',
    changes: [
      '🐛 CSS 选择器从 [vaul-drawer] 改为正确的 [data-vaul-drawer]',
      '🔧 padding-bottom: keyboard-height 让键盘遮住的是空白填充区，内容完整显示在键盘上方',
    ],
  },
  {
    version: '1.066',
    date: '2026-06-06',
    title: '修复 iOS 键盘弹出白框 (JS方案)',
    changes: [
      '🐛 新增 IOSKeyboardFix 组件，用 visualViewport API 检测键盘高度',
      '🔧 Drawer 通过 CSS var(--keyboard-height) 自动上移，消除白色空白',
    ],
  },
  {
    version: '1.065',
    date: '2026-06-06',
    title: '修复 iOS 键盘弹出白屏',
    changes: [
      '🐛 viewport interactiveWidget=resizes-content，键盘开启时布局随之缩减，消除白色空白区',
    ],
  },
  {
    version: '1.064',
    date: '2026-06-06',
    title: '修复编辑交易 Save 按钮被键盘遮住',
    changes: [
      '🐛 EditTransactionSheet Save/Cancel 按钮改为 sticky footer，键盘弹起时始终可见',
    ],
  },
  {
    version: '1.063',
    date: '2026-06-06',
    title: '修复 iOS 点击输入框自动放大',
    changes: [
      '🐛 viewport 加入 maximumScale=1，禁止 iOS Safari 点击 input 时自动 zoom',
    ],
  },
  {
    version: '1.062',
    date: '2026-06-05',
    title: '真正修复编辑交易余额双重扣款',
    changes: [
      '🐛 修复 EditTransactionSheet 手动余额更新代码漏未提交，导致 Vercel 生产版本持续双重扣款',
      '🔧 重写 DB trigger update_account_balance：同户口编辑改为单步原子更新，消除 is_active 条件依赖',
    ],
  },
  {
    version: '1.061',
    date: '2026-06-05',
    title: '修复余额双重更新 (v2)',
    changes: [
      '🐛 移除 TransactionPreview 手动更新余额代码，交由 DB trigger 处理',
      '🐛 移除 BillsClient 手动扣除余额代码，交由 DB trigger 处理',
      '🐛 移除 MakePaymentSheet 手动扣除余额代码，交由 DB trigger 处理',
      '✅ 所有余额变更现统一由 trg_update_account_balance 触发器管理',
    ],
  },
  {
    version: '1.060',
    date: '2026-06-05',
    title: '修复编辑交易后余额 delta 重复计算',
    changes: [
      '🐛 TransactionRow.localTxn 在 sheet 关闭后同步 prop 更新，避免重复开启时用旧 amount 计算 delta',
      '🔧 Public Bank 余额手动修正回 2998.28',
    ],
  },
  {
    version: '1.059',
    date: '2026-06-05',
    title: '修复股票页 FAB 按钮无反应',
    changes: [
      '🐛 修复投资组合/自选股页面 + 按钮点击无效问题（双重函数包装导致）',
    ],
  },
  {
    version: '1.058',
    date: '2026-06-05',
    title: '户口详情页 — 查看各户口交易记录',
    changes: [
      '🏦 点击户口卡片跳转到专属交易记录页',
      '📋 按月份分组显示，含当月净额',
      '✏️🗑️ 编辑/删除按钮不影响跳转',
    ],
  },
  {
    version: '1.057',
    date: '2026-06-05',
    title: '确认交易页新增全局户口选择器',
    changes: [
      '🏦 一次过选择户口，自动应用到所有检测到的交易',
      '✏️ 每笔交易仍可单独展开修改户口',
    ],
  },
  {
    version: '1.056',
    date: '2026-06-05',
    title: '金额限两位小数 + 对账单不自动创建户口',
    changes: [
      '🔢 金额输入框限制最多两位小数（EditTransaction / TransactionPreview / TransferForm）',
      '🚫 对账单解析找不到匹配户口时不再自动创建新户口',
    ],
  },
  {
    version: '1.055',
    date: '2026-06-05',
    title: '对账单支持 JPG/PNG 图片上传（拍照/相册）',
    changes: [
      '📷 对账单上传新增拍照按钮（调用手机相机）',
      '🖼️ 支持从相册上传 JPG/PNG 图片对账单',
      '🤖 parseBankStatementImage — 用银行对账单 prompt 解析图片',
      '🔌 /api/ingest PDF 路径自动路由图片到 parseBankStatementImage',
      '🌐 i18n 更新：zh/en/ms 对账单上传文字',
    ],
  },
  {
    version: '1.054',
    date: '2026-06-05',
    title: '修复预算页行溢出（编辑/删除改图标按钮）',
    changes: [
      '🔧 BudgetRow 编辑/删除按钮改为图标（Pencil/Trash2），减少横向宽度',
      '📱 修复手机上预算行右边按钮被截断的问题',
    ],
  },
  {
    version: '1.053',
    date: '2026-06-05',
    title: '性能优化：骨架屏 + 去重 auth 调用',
    changes: [
      '⚡ getCachedUser() — 用 React.cache() 去重 getUser()，每次页面切换省 ~200ms',
      '💀 新增骨架屏 loading.tsx：Dashboard、交易、户口、账单、预算、贷款、提醒、股票',
      '🔁 Tab 切换时立即显示骨架屏，不再看到空白',
      '🛠️ PageSkeleton.tsx 可复用骨架组件库',
    ],
  },
  {
    version: '1.052',
    date: '2026-06-05',
    title: '修复 PWA 图标空白问题（改用静态 PNG）',
    changes: [
      '🖼️ 生成真实静态 PNG 图标：icon-192x192.png、icon-512x512.png、apple-touch-icon.png',
      '📱 manifest.json 改用 /icons/*.png 静态路径（替代 edge 动态路由）',
      '🍎 layout.tsx apple-touch-icon 改用 /icons/apple-touch-icon.png',
      '🔧 新增 scripts/generate-icons.js 用于重新生成图标',
    ],
  },
  {
    version: '1.051',
    date: '2026-06-05',
    title: '移除各页面右侧悬浮添加按钮',
    changes: [
      '🗑️ 移除所有页面右下角悬浮添加按钮（统一用中间圆形 + 代替）',
      '📈 股票页 FAB 感知 tab：持仓→添加持仓，关注→添加关注，历史→无动作',
      '✅ 涉及页面：账单、户口、预算、贷款、提醒、存钱目标、谁欠我钱、名下资产、股票',
    ],
  },
  {
    version: '1.050',
    date: '2026-06-05',
    title: '修复无限重定向循环',
    changes: [
      '🔁 修复 ERR_TOO_MANY_REDIRECTS 循环（session cookie 过期导致）',
      '🔐 proxy.ts 改用 getUser() 验证 session，防止 stale cookie 导致的死循环',
      '🔓 /api/pwa-icon 加入公开路径，无需登录即可加载 PWA 图标',
    ],
  },
  {
    version: '1.049',
    date: '2026-06-05',
    title: '中间 + 按钮感知当前页面',
    changes: [
      '🎯 中间圆形 + 按钮根据当前页面自动触发对应的添加功能',
      '🏦 户口页 → 添加户口',
      '🏦 贷款页 → 添加贷款',
      '🧾 账单页 → 添加账单',
      '📊 预算页 → 设置预算',
      '🔔 提醒页 → 添加提醒',
      '🎯 存钱目标页 → 添加目标',
      '🤝 谁欠我钱页 → 添加记录',
      '🏠 名下资产页 → 添加资产',
      '📱 其他页面维持默认（添加交易）',
      '🔧 新增 FabContext + useFabAction hook',
    ],
  },
  {
    version: '1.048',
    date: '2026-06-05',
    title: 'PWA 图标修复 — 添加到主屏幕',
    changes: [
      '📱 修复 iPhone 添加到主屏幕显示空白图标问题',
      '🎨 新增动态 PWA 图标 API（/api/pwa-icon/[size]）',
      '✅ 支持 192×192、512×512（Manifest）、180×180（Apple Touch Icon）',
      '🔧 更新 manifest.json 图标引用路径',
    ],
  },
  {
    version: '1.047',
    date: '2026-06-03',
    title: 'Telegram 一键绑定 + 收据相册修复',
    changes: [
      '🔗 Telegram 一键绑定：点按钮自动打开 Bot，用户只需点 START 即绑定',
      '✅ 设置页显示 Telegram 连接状态，支持一键解绑',
      '⏰ Token 15 分钟有效期，过期自动提示重新生成',
      '📸 修复 iPhone Chrome 收据无法选相册（移除 capture=environment）',
    ],
  },
  {
    version: '1.046',
    date: '2026-06-03',
    title: '月薪管理独立模块 + 移除交易面板 EPF/PCB',
    changes: [
      '💼 新增月薪管理页面（菜单 → 月薪管理）',
      '📊 输入月薪自动计算 EPF/SOCSO/EIS/PCB 完整明细',
      '🔘 独立 toggle 选择记录项目（工资、EPF持仓、各项扣款）',
      '💾 一键记录本月工资：同时写入收支交易 + 更新 KWSP-EPF 持仓',
      '🧹 交易确认页移除 EPF/PCB 面板（改到专属模块）',
    ],
  },
  {
    version: '1.045',
    date: '2026-06-03',
    title: '新用户 Onboarding 向导',
    changes: [
      '🎉 新用户首次登录自动跳转至 4 步资料填写向导',
      '👋 Step 1: 姓名、出生日期、性别',
      '📍 Step 2: 州属、职业、月收入',
      '👨‍👩‍👧 Step 3: 婚姻状态、子女人数（影响PCB/税务）',
      '📱 Step 4: 手机/Telegram（可跳过，附功能受限提醒）',
      '⚠️ 跳过时显示警告，说明哪些功能将无法使用',
      '✅ 可后期在 设置→个人资料 补填',
    ],
  },
  {
    version: '1.044',
    date: '2026-06-03',
    title: 'AI 财运分析 + 个人财务评估',
    changes: [
      '🔮 AI 财运分析：生肖 + 星座 + 数字命理，马来西亚华人文化视角',
      '👤 AI 个人财务评估：收入对比、储蓄率、净资产、EPF退休规划、3条建议',
      '📊 Insights 页面升级为 4 Tab：消费分析 · 小票分析 · 财运 · 财务评估',
      '📈 财务评估显示6项关键指标仪表盘（收入/支出/储蓄率/净资产/EPF/DSR）',
    ],
  },
  {
    version: '1.043',
    date: '2026-06-03',
    title: '存钱目标：编辑功能',
    changes: [
      '✏️ 存钱目标卡片新增编辑按钮，可修改名称/表情/颜色/金额/日期',
    ],
  },
  {
    version: '1.042',
    date: '2026-06-03',
    title: '存钱目标：每月需存 + 届时年龄',
    changes: [
      '📅 每张目标卡显示「每月需存 RM X / 月 × N 个月」',
      '🎂 根据出生日期推算目标日期时的年龄（需在设置填写）',
      '📊 顶部汇总新增「每月需存总计」',
      '⚙️ 设置 → 个人资料 新增出生日期字段',
    ],
  },
  {
    version: '1.041',
    date: '2026-06-03',
    title: 'PCB 月扣税自动计算',
    changes: [
      '🏛️ 工资面板新增 PCB（Potongan Cukai Berjadual）月扣税估算',
      '💍 单身 / 已婚切换，自动套用配偶减免 RM4,000',
      '📊 显示年收入、减免合计、应税收入、年税额明细',
      '🔘 独立 toggle：自动记录 PCB 为支出（income_tax 类别）',
      '✅ 到手工资已扣除 EPF + SOCSO + EIS + PCB 合计',
    ],
  },
  {
    version: '1.040',
    date: '2026-06-03',
    title: '3 新模块：存钱目标 · 谁欠我钱 · 名下资产',
    changes: [
      '🎯 存钱目标 — 设定储蓄目标、进度条追踪、一键存入、达成动态',
      '🤝 谁欠我钱 — 记录借出款项、逾期提醒、一键标记已还清',
      '🏠 名下资产 — 房产/车辆/贵重物品/生意资产，估值追踪+增值计算',
      '📱 导航菜单新增 3 个快捷入口',
    ],
  },
  {
    version: '1.039',
    date: '2026-06-03',
    title: 'EPF/SOCSO/EIS 收入来源选择 + 独立开关',
    changes: [
      '💼 新增收入来源选择器（工资 / 副业 / 其他），只有工资才显示 EPF 面板',
      '🔘 EPF、SOCSO、EIS 各自独立 toggle，可单独开关',
    ],
  },
  {
    version: '1.038',
    date: '2026-06-03',
    title: 'EPF / SOCSO / EIS 自动计算',
    changes: [
      '🏦 个人收入确认时自动计算 EPF 11%、SOCSO 0.5%、EIS 0.2%',
      '📊 显示税前工资、各扣款明细、到手工资',
      '📈 开关：自动将 EPF 雇员部分累积至投资组合（KWSP-EPF 持仓）',
      '🛡️ 开关：自动记录 SOCSO + EIS 扣款为支出交易',
      '🎁 投资组合中 KWSP-EPF 持仓新增「申请年度红利」按钮，输入红利率自动计算并记录收入',
    ],
  },
  {
    version: '1.037',
    date: '2026-06-03',
    title: 'AI 消费分析 — 小票图片分析',
    changes: [
      '📸 AI 消费分析页面新增「小票分析」tab',
      '🖼️ 上传收据照片 → Gemini Vision 分析商家、金额、商品明细',
      '💬 AI 点评消费是否合理，马来西亚风格',
      '📤 分析结果可分享或复制',
    ],
  },
  {
    version: '1.036',
    date: '2026-06-03',
    title: 'AI 建议刷新按钮（每日限 5 次）',
    changes: [
      '🔄 AI 今日理财建议右上角加刷新按钮，显示今日剩余次数（5/5）',
      '🔒 每天最多刷新 5 次，次数记录在 localStorage，按日重置',
      '⬜ 达到上限后按钮变灰不可点',
    ],
  },
  {
    version: '1.035',
    date: '2026-06-03',
    title: 'AI 理财建议 + 世界名人名言',
    changes: [
      '📖 AI 每日理财建议新增世界名人名言（巴菲特、芒格、彼得林奇等）',
      '💡 格式：个人化建议 + 名言引用 + 与用户当前状况的关联',
    ],
  },
  {
    version: '1.034',
    date: '2026-06-03',
    title: 'Dashboard 可自定义 Widget',
    changes: [
      '⚙️ Dashboard 新增「财务概览」区域，5 个可开关 Widget',
      '🧾 Widget 1：每月固定支出（账单 + 贷款月供汇总）',
      '📊 Widget 2：月度预算进度条',
      '📈 Widget 3：总预计支出 = 固定 + 预算范围（RM 5000 ～ RM 7000）',
      '🔔 Widget 4：未来 7 天到期提醒',
      '🤖 Widget 5：AI 每日理财建议（Gemini Flash，1 小时缓存）',
      '🔧 点「⚙️ 自定义」可开关每个 Widget，设定保存在 localStorage',
    ],
  },
  {
    version: '1.033',
    date: '2026-06-03',
    title: '每月账单 + 贷款月供合并总览',
    changes: [
      '📊 每月账单顶部新增「每月固定总支出」汇总卡：账单合计 + 贷款月供 = 总固定支出',
      '🏦 页面底部显示所有贷款月供（只读），含下次还款日和金额',
      '🔗 贷款区域右上角「管理 →」跳转贷款页面',
      '✅ 两个页面各自保持独立，不合并，不乱',
    ],
  },
  {
    version: '1.032',
    date: '2026-06-03',
    title: '黄金 RM/克 实时价格',
    changes: [
      '🟡 新增特殊 ticker: GOLD-MYR-GRAM — 实时获取 XAU/USD × USD/MYR ÷ 31.1035 = RM/克',
      '🥇 黄金默认货币改为 MYR，快选第一项为「黄金 RM/克（实时）」',
      '📊 持仓卡片显示 RM XX.XX/g 格式',
    ],
  },
  {
    version: '1.031',
    date: '2026-06-03',
    title: '账单缴付频率（每 1-12 个月）',
    changes: [
      '📅 账单支持每月/每2月/每3月/每4月/每6月/每年缴付',
      '💰 实付金额 = 月均金额 × 频率（如月均 RM195.8 × 3 = RM587.40）',
      '🃏 账单卡片显示实付金额 + 月均金额',
      '💳 扣款按钮显示当次实付总额',
      '⚠️ 需在 Supabase 执行：ALTER TABLE monthly_bills ADD COLUMN IF NOT EXISTS frequency_months INTEGER DEFAULT 1;',
    ],
  },
  {
    version: '1.030',
    date: '2026-06-03',
    title: '每月账单自动扣户口',
    changes: [
      '💳 账单表单新增「自动扣户口」选择器，可选现有户口',
      '🟢 账单卡片底部出现「从 XX 扣款」按钮',
      '💰 点击扣款 → 自动记录支出交易 + 扣除户口余额',
      '⚠️ 需在 Supabase 执行：ALTER TABLE monthly_bills ADD COLUMN IF NOT EXISTS auto_deduct_account TEXT;',
    ],
  },
  {
    version: '1.029',
    date: '2026-06-03',
    title: '信用卡还款提醒',
    changes: [
      '💳 信用卡户口新增「每月还款日」字段',
      '🔔 余额为负 + 设了还款日 → 出现「添加至账单提醒」开关',
      '📅 开启后自动创建每月提醒，到期前 3 天通知还款金额',
      '⚠️ 需在 Supabase 执行：ALTER TABLE accounts ADD COLUMN IF NOT EXISTS due_day INTEGER;',
    ],
  },
  {
    version: '1.028',
    date: '2026-06-03',
    title: '类别调整',
    changes: [
      '🗑️ 删除「马来餐厅」类别（旧交易保留历史显示）',
      '🍽️ 「餐厅」→「吃」',
      '☕ 「咖啡饮料」→「喝」',
      '🛍️ Shopee + Lazada 合并为「网购」（Lazada 保留为历史别名）',
      '🏡 新增「家用」类别',
      '🛋️ 新增「家具」类别',
    ],
  },
  {
    version: '1.027',
    date: '2026-06-03',
    title: '还款后自动推进账单提醒',
    changes: [
      '🔔 点击「还款」后，对应账单提醒自动推进到下一期（不再标记为已完成）',
      '🔍 匹配提醒方式：linked_loan_id 或标题含贷款名称（兼容手动创建的提醒）',
      '📅 每月提醒 → 下次日期 +1 个月；每年提醒 → +12 个月；一次性提醒 → 标记完成',
    ],
  },
  {
    version: '1.026',
    date: '2026-06-03',
    title: '投资组合升级：黄金/ETF/基金/加密货币',
    changes: [
      '🔄 「股票」模块更名为「投资」，支持 6 种资产类型',
      '📈 股票：KLSE(.KL) / 美股 / 港股(.HK)',
      '🔵 ETF：SPY / QQQ / MyETF',
      '🟡 黄金：GC=F（期货）/ XAUUSD=X / GLD ETF',
      '₿ 加密货币：BTC-USD / ETH-USD 等（Yahoo Finance 实时价）',
      '📊 基金/ASB：手动 NAV 录入，无实时价格',
      '🏷️ 每张持仓卡片显示资产类型 badge + 正确货币符号',
      '⚠️ 需在 Supabase 执行：ALTER TABLE stock_holdings ADD COLUMN IF NOT EXISTS asset_type TEXT DEFAULT \'stock\';',
    ],
  },
  {
    version: '1.025',
    date: '2026-06-03',
    title: '4 大功能升级',
    changes: [
      '🏦 贷款添加/编辑：新增「添加至账单提醒」和「添加至月度预算」开关',
      '📊 月度预算：每行新增「编辑」「删除」按钮',
      '📋 LHDN 税务：新增「缴税记录」tab，支持 PCB（12 月）和 CP500（6 期）录入',
      '⚙️ Menu 自定义排序：点「⚙️ 自定义排序」用 ↑↓ 调整 Menu 项目顺序，自动保存',
      '⚠️ CP500/PCB 需在 Supabase 建表：CREATE TABLE tax_payments ...',
    ],
  },
  {
    version: '1.024',
    date: '2026-06-03',
    title: '每月账单页面',
    changes: [
      '🧾 新增「每月账单」页面（Menu 第一位）',
      '➕ 可添加固定账单：TNB、Unifi、水费、Maintenance 等，带快选预设',
      '✏️ 可编辑 / 删除已有账单',
      '🔔 开关「添加至账单提醒」：自动创建每月提醒，到期前 3 天通知',
      '📊 开关「添加至月度预算」：自动更新当月该类别预算金额',
      '📅 账单按到期日排序，标记「⚡ X 天后到期」',
      '⚠️ 需在 Supabase SQL Editor 建表：CREATE TABLE monthly_bills ...',
    ],
  },
  {
    version: '1.023',
    date: '2026-06-03',
    title: '修复还款日期计算',
    changes: [
      '📅 下次还款日改用贷款原定日期推算（不再用付款当天日期），月份固定在同一天',
      '🔧 修复 advanceMonths 月末溢出：Jan 31 + 1 月 → Feb 28（不再跑到 Mar 3）',
    ],
  },
  {
    version: '1.022',
    date: '2026-06-03',
    title: '还款时选择户口',
    changes: [
      '🏦 贷款还款页面：新增户口选择器，显示各户口余额',
      '💳 还款记录 account_name 使用所选户口（不再写死 Cash）',
      '💰 还款后自动从所选户口余额扣除还款金额',
    ],
  },
  {
    version: '1.021',
    date: '2026-06-03',
    title: '内部转账支持',
    changes: [
      '↔️ 新增「转账」tab：直接录入自己户口之间的转账（From → To + 金额 + 日期）',
      '🚫 内部转账不再计入收入/支出统计，只更新两个户口余额',
      '🏦 TransactionPreview：选 Transfer 类型时显示 From / To 两个账户选择',
      '🔧 保存逻辑：transfer 类型正确执行 from_balance -= amount, to_balance += amount',
    ],
  },
  {
    version: '1.020',
    date: '2026-06-03',
    title: '户口表单字段更新',
    changes: [
      '✏️ 编辑户口表单："后4位数字（选填）" → "户口号码（选填）"（支持完整户口号）',
    ],
  },
  {
    version: '1.019',
    date: '2026-06-03',
    title: 'Menu 点击后自动关闭 + 路由优化',
    changes: [
      '🔧 点击 Menu 里任何菜单项后，底部抽屉自动关闭',
      '⚡ proxy.ts middleware 改用 getSession()（只读 cookie），替代 getUser()（需网络请求），减少约 40ms 延迟',
    ],
  },
  {
    version: '1.017',
    date: '2026-06-02',
    title: '修复 Telegram 语音/图片无响应',
    changes: [
      '🐛 根本原因：确认按钮 callback_data 超过 Telegram 64 字节限制，导致消息发送失败',
      '⚡ Vercel 函数超时上调至 60 秒（默认 10 秒会杀掉慢的语音处理）',
      '🗜️ 紧凑编码：type=1字符, 日期=MM-DD, 名字截断 12 字符',
      '🛡️ 兜底机制：如果按钮消息发送失败，直接保存交易并通知用户',
      '🔁 回调点击后立即响应"正在保存..."，按钮不再卡住',
    ],
  },
  {
    version: '1.016',
    date: '2026-06-01',
    title: '优化语音处理速度',
    changes: [
      '⚡ 文件下载超时限制 10 秒，防止卡死',
      '⚡ Gemini 重试间隔从 1s/2s 缩短为 500ms/1s',
    ],
  },
  {
    version: '1.015',
    date: '2026-06-01',
    title: '恢复使用 flash-lite 模型',
    changes: [
      '⚡ 语音和图片识别恢复使用 gemini-2.5-flash-lite（更快、更省费用）',
      '📝 保留改进后的语音提示词（金额规则、马来西亚食品词汇）',
    ],
  },
  {
    version: '1.014',
    date: '2026-06-01',
    title: '语音/图片识别升级至 Gemini Flash 标准版',
    changes: [
      '🧠 语音和图片识别改用 gemini-2.5-flash（标准版），比 flash-lite 更准确',
      '📝 语音提示词强化金额识别：lima=RM5 而非 RM500，食物价格区间 RM3-30',
      '🗣️ 新增常见马来西亚食品词汇：da chang 大肠、tau foo fa 豆腐花等',
      '🌡️ 语音/图片模型温度从 0.1 调整至 0.2（对模糊语音更宽容）',
    ],
  },
  {
    version: '1.013',
    date: '2026-06-01',
    title: 'Telegram 确认按钮：防止语音/图片误识别',
    changes: [
      '✅ 语音和图片解析后不立即保存，先显示 [✅ Save] [❌ Discard] 确认按钮',
      '📝 文字输入仍然直接保存（文字准确率高）',
      '🔍 确认消息显示完整解析结果：名称、金额、日期、账户、类别',
      '⚡ Telegram Webhook 新增 callback_query 事件处理',
    ],
  },
  {
    version: '1.012',
    date: '2026-05-31',
    title: 'Telegram 机器人：/link 命令 + 图片/语音修复',
    changes: [
      '🔗 新增 /link 邮箱 命令：无需打开 App，直接在 Telegram 绑定账号',
      '📸 图片识别修复：明确使用 image/jpeg MIME 类型（Telegram 图片统一为 JPEG）',
      '🎤 语音识别修复：明确使用 audio/ogg MIME 类型（Telegram 语音消息为 OGG Opus）',
      '🛡️ 增加 try/catch 错误捕获，图片/语音处理失败时返回友好提示',
    ],
  },
  {
    version: '1.011',
    date: '2026-05-31',
    title: '修复 Telegram/WhatsApp 机器人用户识别失败',
    changes: [
      '🔧 Webhook 改用管理员客户端（service role）查询 profiles 表——匿名请求被 RLS 阻止导致无法识别用户，这就是"账号未绑定"错误的根本原因',
    ],
  },
  {
    version: '1.010',
    date: '2026-05-31',
    title: 'Telegram 机器人（替换 WhatsApp）',
    changes: [
      '🤖 新增 Telegram 机器人：文字/图片/语音记账，/undo /report /help 命令',
      '⚙️ 设置页面新增 Telegram ID 绑定入口',
      '🔧 中间件白名单新增 /api/telegram 路径',
      '🗑️ WhatsApp 保留但不再主推（Meta 验证门槛太高）',
    ],
  },
  {
    version: '1.009',
    date: '2026-05-31',
    title: '修复 WhatsApp Webhook 验证失败',
    changes: [
      '🔧 将 /api/whatsapp 路径加入中间件白名单，解决 Meta 验证时被重定向到登录页的问题',
    ],
  },
  {
    version: '1.008',
    date: '2026-05-31',
    title: 'WhatsApp 机器人升级',
    changes: [
      '💬 WhatsApp 机器人功能完善：UNDO（10分钟内撤销）、REPORT（7天摘要）、HELP 命令',
      '🎤 支持 WhatsApp 语音消息记账（直接发送语音，AI 转录并解析）',
      '📸 支持发送收据图片到 WhatsApp 自动识别并记录',
    ],
  },
  {
    version: '1.007',
    date: '2026-05-31',
    title: '搜索 + CSV导出 + 资料编辑 + 修复',
    changes: [
      '🔍 交易搜索：在交易页面按商家名/描述搜索',
      '⬇ CSV 导出：交易页面右上角可按月导出 CSV 文件',
      '👤 资料编辑：设置页面可修改姓名和 WhatsApp 手机号码',
      '🔧 编辑交易表单：修复所有硬编码中文字符串，改为多语言支持',
      '🛡️ 稳健查询：即使 ledger 数据库列尚未添加，交易记录也能正常显示',
    ],
  },
  {
    version: '1.006',
    date: '2026-05-31',
    title: '修复构建错误（TypeScript）',
    changes: [
      '🔧 修复 TypeScript 类型推断错误导致 Vercel 构建失败（投资解析器 filter 参数缺少类型标注）',
    ],
  },
  {
    version: '1.005',
    date: '2026-05-31',
    title: '修复净资产计算（不含贷款）',
    changes: [
      '🔧 净资产（户口页面）不再计入贷款与债务金额——贷款已在"贷款与债务"页面单独追踪',
      '💡 总负债仅反映余额为负数的户口（如信用卡透支），不含房贷、车贷等',
    ],
  },
  {
    version: '1.004',
    date: '2026-05-31',
    title: '商业模式 + AI 分析 + 投资同步 + WhatsApp',
    changes: [
      '🏪 个人/商业账本切换：每笔交易可标记 Personal 或 Business，仪表盘显示业务营业额、支出、净利润及利润率',
      '🤖 AI 消费分析（Roast My Spending）：Gemini 分析过去 7 天消费，用幽默 Manglish 风格生成个人化报告，可分享',
      '📈 投资对账单同步：上传 Moomoo/AHAM/EPF/Rakuten PDF，自动解析交易并更新持股（加权平均成本）',
      '💬 WhatsApp 机器人：发送文字或收据照片给 WhatsApp 号码，自动记账并回复确认',
      '🔧 修复预算页面 UTC+8 时区偏移导致月份范围错误',
      '🔧 修复提醒页面今日/逾期判断 UTC+8 偏移问题',
      '🔧 修复 AI 解析器回退日期和 AI 提示词使用马来西亚时区',
      '⚡ 编辑交易后使用 router.refresh() 替换 window.location.reload()，消除页面闪烁',
      '🔁 Gemini AI 调用加入自动重试（指数退避，最多 2 次），减少偶发超时失败',
      '🗂️ 快速添加增加第 5 个标签：📈 投资（上传经纪商/基金 PDF）',
      '📋 交易列表新增 Personal/Business 筛选标签',
    ],
  },
  {
    version: '1.003',
    date: '2026-05-30',
    title: '通知 + 语音 + UI 优化',
    changes: [
      '🔔 新增 App 推送通知（Web Push）和邮件提醒',
      '🎤 语音识别升级：直接发音频给 Gemini AI，支持 Rojak 混合语言（中文+马来文+英文）、各种口音（马来、华人、印度）',
      '🗓️ 修复每月提醒日期计算错误（UTC+8 时区偏移）',
      '🔘 统一所有模块的添加按钮样式（绿色长方形圆角，固定底部）',
      '🌐 预算类别名称支持多语言翻译',
      '🏦 银行对账单 PDF 导入时自动识别并关联户口',
      '📋 添加 Changelog 页面（就是这里！）',
    ],
  },
  {
    version: '1.002',
    date: '2026-05-29',
    title: '户口 & 股票模块',
    changes: [
      '🏦 全新户口（Accounts）模块：追踪银行、电子钱包、投资、信用卡等户口',
      '📊 净资产总览：资产 vs 负债实时计算',
      '📈 股票组合追踪：Yahoo Finance 实时股价、未实现盈亏',
      '👀 自选股关注列表：设定目标价格，接近时提醒',
      '📋 交易记录历史',
      '🗂️ 底部导航重组：预算移至"更多"，户口成为主导航',
    ],
  },
  {
    version: '1.001',
    date: '2026-05-28',
    title: '多语言 & 动画',
    changes: [
      '🌍 支持三语言切换：中文、English、Bahasa Malaysia',
      '🗣️ 语音识别根据语言自动切换识别语言',
      '📄 PDF 银行对账单批量导入交易记录',
      '🎉 保存交易时显示庆祝动画（💰🎊✨）',
      '📭 空状态页面添加浮动 emoji 动画',
      '🏷️ 交易类别名称支持多语言',
    ],
  },
  {
    version: '1.000',
    date: '2026-05-27',
    title: '初始发布',
    changes: [
      '💸 AI 智能交易记录：文字、语音、收据拍照、PDF 导入',
      '📊 仪表盘：月度收支概览、趋势图表',
      '🏷️ 37 个马来西亚本地消费类别',
      '📅 月度预算管理：设定并追踪各类别消费上限',
      '🏦 贷款与债务追踪：减息法、固定利率、伊斯兰融资',
      '🔔 账单提醒：每日/每周/每月/每年循环提醒',
      '🧾 马来西亚所得税减免追踪（LHDN）',
      '🌙 深色模式支持',
      '📱 PWA：可安装到手机主屏幕',
    ],
  },
]
